id: PA323A92B
initial_creation_type: input
source_metadata:
  title: Works of Tsarchen Losal Gyatso
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    bcd2:
      title: རྗེ་བཙུན་རིན་པོ་ཆེ་བསོད་ནམས་རྩེ་མོའི་རྣམ་པར་ཐར་པ་དོན་གྱི་སྙིང་པོ་བསྡུས་པ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: bcd2.txt
      order: 1
    844d:
      title: དཔལ་ལྡན་བླ་མ་དམ་པ་ཀུན་སྤངས་ཆོས་ཀྱི་རྒྱལ་པོའི་རྣམ་པར་ཐར་པ་ངོ་མཚར་དད་པའི་སྤུ་ལོང་གཡོ་བ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 844d.txt
      order: 2
    0a74:
      title: རང་གི་རྟོགས་པ་བརྗོད་པ་ལམ་གླུ་དཔྱིད་ཀྱི་རྒྱལ་མོའི་གླུ་དབྱངས།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 0a74.txt
      order: 3
    3b26:
      title: རྗེ་བཙུན་ཀུན་སྤངས་ཆེན་པོ་ལ་བསྟོད་པ་མཐའ་ཡས་མ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 3b26.txt
      order: 4
    82f6:
      title: རྗེ་བཙུན་རྡོ་རྗེ་འཆང་ཆེན་པོ་ལ་ཝ་བྷུ་ཏི་པའི་རྣམ་ཐར་བསྟོད་པ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 82f6.txt
      order: 5
    12cc:
      title: རྡོ་རྗེ་འཆང་སྒོ་རུམ་པ་ཆེན་པོའི་རྣམ་ཐར་གསོལ་འདེབས་བྱང་ཕྱོགས་མཁས་གྲུབ་མ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 12cc.txt
      order: 6
    b494:
      title: རྗེ་བཙུན་འཁྲུལ་ཞིག་ཀ་བཞི་པའི་ཞལ་སྔ་ནས་ལ་གསོལ་འདེབས།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: b494.txt
      order: 7
    b818:
      title: མཁས་བཙུན་གྲུབ་པའི་དབང་ཕྱུག་རྗེ་བཙུན་བློ་གསལ་རྒྱ་མཚོའི་མགུར་འབུམ་གྱི་ཚོགས་ལམ་བཟང་གསལ་བའི་འོད་སྣང་།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: b818.txt
      order: 8
    250f:
      title: རྗེ་བཙུན་འབྲོག་མི་ལོ་ཙཱ་བ་ལ་བསྟོད་པ་སྙན་བརྒྱུད་ཀྱི་པད་མཚོ་བཞད་པ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 250f.txt
      order: 9
    40de:
      title: འཇམ་དབྱངས་འཁོན་སྟོན་ལ་བསྟོད་པ།
      author: ཚར་ཆེན་བློ་གསལ་རྒྱ་མཚོ།
      base_file: 40de.txt
      order: 10
created_at: '2022-04-06T17:11:08.848800'
last_modified_at: '2022-04-06T17:11:08.848812'
